version: '3.2'

services:
  app:
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/server.pid
    ports:
      - 9000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      REDIS_URL: redis://redis:6379
    build: .
    depends_on:
      - db
    volumes:
      # Mounts the app code (".") into the container's "/app" folder:
      - .:/app:delegated

  redis:
    image: redis:3.2.8
    environment:
      REDIS_URL: redis://redis:6379

  db:
    image: postgres:9.6-alpine
    ports:
      - 10033:5432

volumes:
  db-data:
  app-gems:
    driver: local
